# Linear Algebra with Python for ML

To do linear algebra appropriatelly we need Numpy (may need to `pip install numpy` or `conda install numpy` it first). Then import it into your script, command line operation or notebook.

In [1]:
import numpy as np

Matrices are formed using the `array` method; row after row, as above. Note how many and what type of brackets are used in this syntax.

In [4]:
A = np.array([[121, 21], [57, 57] , [78, 32], [11, 66]])
print('A = ', A)

A =  [[121  21]
 [ 57  57]
 [ 78  32]
 [ 11  66]]


Column vectors are called in the same way

In [12]:
y = np.array([[460], [232], [315], [178]])

Vectors can also be built using the `array` method:

In [9]:
a = np.array([1, 2, 3, 4])

Dimensions can be checked by using the `.shape`:

In [10]:
print('matrix A is of dimensions ', A.shape)
print('column vector y is of dimensions ', y.shape)
print('vector a is of dimensions ', a.shape)

matrix A is of dimensions  (4, 2)
column vector y is of dimensions  (4, 1)
vector a is of dimensions  (4,)


## Slicing
Accessing particular values in the matrix. **Note**, that Python is 0-indexing! 

**[Row, Column]**

In [13]:
A = np.array([[121, 21], [57, 57] , [78, 32], [11, 66]])

print(A)

[[121  21]
 [ 57  57]
 [ 78  32]
 [ 11  66]]


In [20]:
A[2,0] # Second (third) row, first (0th) collumn

78

In [21]:
A[:,0] # slice whole first (0th) column by ':'.

array([121,  57,  78,  11])

## Matrix addittion and substraction

matrix and matrix

In [24]:
A = np.array([[1, 0], [2, 5], [3, 1]])
B = np.array([[4, 0.5], [2, 5], [0, 1]])

print(A + B)

[[ 5.   0.5]
 [ 4.  10. ]
 [ 3.   2. ]]


In [25]:
print(A - B)

[[-3.  -0.5]
 [ 0.   0. ]
 [ 3.   0. ]]


## Scalar by matrix multiplication and division

In [26]:
print(3 * A)

[[ 3  0]
 [ 6 15]
 [ 9  3]]


In [27]:
print(A / 3)

[[0.33333333 0.        ]
 [0.66666667 1.66666667]
 [1.         0.33333333]]


## Combination

In [29]:
a = np.array([[1], [4], [2]])
b = np.array([[0], [0], [5]])
c = np.array([[3], [0], [2]])

print(3 * a + b - c /3)

[[ 2.        ]
 [12.        ]
 [10.33333333]]


## Matrix x vector multiplication

Unlike MATLAB Python's matrix * column vector (n\*1 matrix) is not default and one has to use dot function. 

**Note** the dimensions that must be used for this operation; **[m\*n] x [n\*1] = [m\*1]**

In [34]:
A = np.array([[1, 3], [4, 0], [2, 1]])
b = np.array([[1], [5]])

print(np.dot(A, b))

print('A is of dim', A.shape)
print('b is of dim', b.shape)

[[16]
 [ 4]
 [ 7]]
A is of dim (3, 2)
b is of dim (2, 1)


Vector x matrix for `h(theta)`

In [37]:
X = np.array([[1, 2104], [1, 1416], [1, 1534], [1, 852]])
h = np.array([[-40], [.25]])

print(np.dot(X,h))

[[486. ]
 [314. ]
 [343.5]
 [173. ]]


## Matrix x Matrix multiplication

is pretty much like matrix x vector, but two columns are bound.

**Note** the dimensions **[m\*n] x [n\*o] = [m\*o]**

In [39]:
A = np.array([[1, 3, 2], [4, 0, 1]])
B = np.array([[1, 3], [0, 1], [5, 2]])

print(np.dot(A, B))

[[11 10]
 [ 9 14]]


## Identity Matrix

In [42]:
I = np.eye(3,3)

print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Inverse

We need to import from `numpy.linalg`, **note**, that `inv` will only work for square matrixes while `pinv` for any dimensions:

In [48]:
from numpy.linalg import pinv

Ainv = pinv(A)

print(Ainv)

[[-0.03465347  0.24752475]
 [ 0.25247525 -0.08910891]
 [ 0.13861386  0.00990099]]


## Transpose

In [52]:
print(A.transpose())

[[1 4]
 [3 0]
 [2 1]]
